updated cicd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,8 +24,13 @@ jobs:
       - name: Download Kaggle dataset
         run: |
           mkdir -p kaggle/input
-          kaggle datasets download notshrirang/spotify-million-song-dataset -p kaggle/input/ --unzip
-          kaggle datasets download rodolfofigueroa/spotify-12m-songs -p kaggle/input/ --unzip
+          kaggle datasets download -p kaggle/input/ --unzip notshrirang/spotify-million-song-dataset 
+          kaggle datasets download -p kaggle/input/ --unzip rodolfofigueroa/spotify-12m-songs
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to download Kaggle datasets."
+            exit 1
+          fi
+          ls kaggle/input/
         env:
           KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
           KAGGLE_KEY: ${{ secrets.KaggleKey }}
